"""
Financial Sentiment Lexicons (Loughran-McDonald Dictionary).
Extracted from nlp_advanced.py for modularity.

Reference: Loughran, T. and McDonald, B. (2011).
"When is a Liability not a Liability?"
https://sraf.nd.edu/loughranmcdonald-master-dictionary/
"""

# Core financial sentiment words from Loughran-McDonald (2011) dictionary

FINANCIAL_POSITIVE = {
    # Strong positive
    "achieve", "achieved", "achieves", "achieving", "accomplishment", "accomplishments",
    "advantage", "advantages", "breakthrough", "breakthroughs", "benefit", "benefits",
    "beneficial", "boom", "booming", "bullish", "confident", "confidence",
    "creative", "creativity", "deliver", "delivered", "delivers", "delivering",
    "earnings", "efficient", "efficiency", "enable", "enabled", "enables",
    "enhance", "enhanced", "enhances", "enhancing", "excellent", "exceptional",
    "excite", "excited", "exciting", "exclusive", "expansion", "favorable",
    "gain", "gained", "gaining", "gains", "good", "great", "greater", "greatest",
    "grow", "growing", "grown", "grows", "grew", "growth", "higher", "highest", "improve",
    "improved", "improvement", "improvements", "improves", "improving", "increase",
    "increased", "increases", "increasing", "innovation", "innovations", "innovative",
    # Growth/comparison indicators
    "up", "bigger", "larger", "more", "added", "boost", "boosted", "boosting", "boosts",
    "expand", "expanded", "expanding", "expands", "extend", "extended", "extending",
    "extends", "hike", "hiked", "hikes", "hiking", "jump", "jumped", "jumping", "jumps",
    "climb", "climbed", "climbing", "climbs", "double", "doubled", "doubles", "doubling",
    "triple", "tripled", "triples", "tripling", "accelerate", "accelerated", "accelerates",
    "accelerating", "acceleration", "advance", "advanced", "advances", "advancing",
    "leading", "leader", "leadership", "leverage", "leveraged", "leveraging",
    "momentum", "opportunities", "opportunity", "optimal", "optimism", "optimistic",
    "outperform", "outperformed", "outperforming", "outperforms", "outstanding",
    "positive", "positively", "premium", "profitable", "profitability", "profit",
    "profits", "progress", "progressed", "progresses", "progressing", "promising",
    "prosper", "prospered", "prospering", "prosperity", "prosperous", "rally",
    "rallied", "rallies", "rallying", "recover", "recovered", "recovering",
    "recovers", "recovery", "record", "rebound", "rebounded", "rebounding",
    "reward", "rewarded", "rewarding", "rewards", "rise", "risen", "rises", "rose",
    "rising", "robust", "solid", "soar", "soared", "soaring", "soars",
    "stabilize", "stabilized", "stabilizes", "stabilizing", "stable", "stellar",
    "strength", "strengthen", "strengthened", "strengthening", "strengthens",
    "strong", "stronger", "strongest", "succeed", "succeeded", "succeeding",
    "succeeds", "success", "successes", "successful", "successfully", "superior",
    "surge", "surged", "surges", "surging", "surpass", "surpassed", "surpasses",
    "surpassing", "sustainable", "thriving", "top", "transform", "transformed",
    "transforming", "transforms", "turnaround", "upbeat", "upgrade", "upgraded",
    "upgrades", "upgrading", "upturn", "upward", "upwards", "win", "winner",
    "winning", "wins", "won",
}

FINANCIAL_NEGATIVE = {
    # Strong negative
    "abandon", "abandoned", "abandoning", "abandons", "abnormal", "abuse",
    "accident", "accidents", "accuse", "accused", "accuses", "accusing",
    "adverse", "adversely", "against", "allegation", "allegations", "allege",
    "alleged", "allegedly", "alleges", "alleging", "annul", "annulled",
    "annulling", "annuls", "anomalous", "anomaly", "anxious", "anxiety",
    "attack", "attacked", "attacking", "attacks", "bad", "bail", "bailout",
    "bankrupt", "bankruptcies", "bankruptcy", "bear", "bearish", "blame",
    "blamed", "blames", "blaming", "breach", "breached", "breaches", "breaching",
    "burden", "burdened", "burdening", "burdens", "catastrophe", "catastrophic",
    "caution", "cautionary", "cautious", "cautiously", "challenge", "challenged",
    "challenges", "challenging", "chaos", "chaotic", "claim", "claims",
    "closure", "closures", "collapse", "collapsed", "collapses", "collapsing",
    "compete", "competes", "competing", "competition", "competitive", "complaint",
    "complaints", "concern", "concerned", "concerning", "concerns", "conflict",
    "conflicts", "constrain", "constrained", "constraining", "constrains",
    "constraint", "constraints", "contraction", "crash", "crashed", "crashes",
    "crashing", "crime", "criminal", "crisis", "critical", "criticism",
    "criticisms", "criticize", "criticized", "criticizes", "criticizing",
    "crucial", "cut", "cutback", "cutbacks", "cuts", "cutting", "damage",
    "damaged", "damages", "damaging", "danger", "dangerous", "dangerously",
    "dangers", "deadlock", "deadlocked", "deadlocking", "deadlocks", "death",
    "deaths", "debt", "debts", "deceive", "deceived", "deceives", "deceiving",
    "decline", "declined", "declines", "declining", "decrease", "decreased",
    "decreases", "decreasing", "default", "defaulted", "defaulting", "defaults",
    "defect", "defective", "defects", "deficit", "deficits", "delay", "delayed",
    "delaying", "delays", "demise", "demolish", "demolished", "demolishes",
    "demolishing", "deny", "denied", "denies", "denying", "deplete", "depleted",
    "depletes", "depleting", "depletion", "depreciate", "depreciated",
    "depreciates", "depreciating", "depreciation", "depressed", "depression",
    "destabilize", "destabilized", "destabilizes", "destabilizing", "destroy",
    "destroyed", "destroying", "destroys", "destruction", "destructive",
    "deteriorate", "deteriorated", "deteriorates", "deteriorating", "deterioration",
    "devastating", "devastation", "difficult", "difficulties", "difficulty",
    "dilute", "diluted", "dilutes", "diluting", "dilution", "diminish",
    "diminished", "diminishes", "diminishing", "dire", "disappoint", "disappointed",
    "disappointing", "disappointingly", "disappointment", "disappointments",
    "disappoints", "disaster", "disasters", "disastrous", "disclaim", "disclaimer",
    "disclaimers", "disclaims", "disclose", "disclosed", "discloses", "disclosing",
    "disclosure", "disclosures", "discontinue", "discontinued", "discontinues",
    "discontinuing", "discourage", "discouraged", "discourages", "discouraging",
    "dispute", "disputed", "disputes", "disputing", "disrupt", "disrupted",
    "disrupting", "disruption", "disruptions", "disruptive", "disrupts",
    "distress", "distressed", "distresses", "distressing", "divest", "divested",
    "divesting", "divestiture", "divestitures", "divests", "doubt", "doubted",
    "doubtful", "doubting", "doubts", "down", "downgrade", "downgraded",
    "downgrades", "downgrading", "downturn", "downturns", "downward", "downwards",
    "drag", "dragged", "dragging", "drags", "drain", "drained", "draining",
    "drains", "drop", "dropped", "dropping", "drops", "drought", "droughts",
    "dull", "dump", "dumped", "dumping", "dumps", "erode", "eroded", "erodes",
    "eroding", "erosion", "error", "errors", "evade", "evaded", "evades",
    "evading", "evasion", "exacerbate", "exacerbated", "exacerbates", "exacerbating",
    "excessive", "excessively", "exit", "exited", "exiting", "exits", "expire",
    "expired", "expires", "expiring", "expose", "exposed", "exposes", "exposing",
    "exposure", "exposures", "fail", "failed", "failing", "fails", "failure",
    "failures", "fall", "fallen", "falling", "falls", "fell", "false", "falsely",
    "falsification", "falsifications", "falsified", "falsifies", "falsify",
    "falsifying", "fatal", "fatalities", "fatality", "fault", "faulted",
    "faulting", "faults", "faulty", "fear", "feared", "fearful", "fearing",
    "fears", "felonies", "felony", "fine", "fined", "fines", "fining", "fire",
    "fired", "fires", "firing", "flaw", "flawed", "flaws", "flee", "fleeing",
    "flees", "fled", "fluctuate", "fluctuated", "fluctuates", "fluctuating",
    "fluctuation", "fluctuations", "fraud", "frauds", "fraudulent", "fraudulently",
    "grim", "halt", "halted", "halting", "halts", "hamper", "hampered",
    "hampering", "hampers", "harm", "harmed", "harmful", "harmfully", "harming",
    "harms", "harsh", "harshly", "hazard", "hazardous", "hazards", "hinder",
    "hindered", "hindering", "hinders", "hurt", "hurting", "hurts", "idle",
    "idled", "idling", "ignore", "ignored", "ignores", "ignoring", "illegal",
    "illegally", "impair", "impaired", "impairing", "impairment", "impairments",
    "impairs", "impediment", "impediments", "implode", "imploded", "implodes",
    "imploding", "implosion", "inability", "inadequate", "inadequately",
    "insolvent", "instability", "insufficient", "insufficiently", "interrupt",
    "interrupted", "interrupting", "interruption", "interruptions", "interrupts",
    "investigation", "investigations", "issue", "issues", "jeopardize",
    "jeopardized", "jeopardizes", "jeopardizing", "jeopardy", "lack", "lacked",
    "lacking", "lacks", "lag", "lagged", "lagging", "lags", "late", "later",
    "latest", "lawsuit", "lawsuits", "layoff", "layoffs", "liability",
    "liabilities", "liquidate", "liquidated", "liquidates", "liquidating",
    "liquidation", "liquidations", "litigate", "litigated", "litigates",
    "litigating", "litigation", "litigations", "lose", "losing", "loss",
    "losses", "lost", "low", "lower", "lowered", "lowering", "lowers", "lowest",
    "manipulation", "manipulations", "meltdown", "miss", "missed", "misses",
    "missing", "mistake", "mistaken", "mistakes", "mitigate", "mitigated",
    "mitigates", "mitigating", "mitigation", "negative", "negatively", "neglect",
    "neglected", "neglecting", "neglects", "obstacle", "obstacles", "obsolete",
    "ominous", "overdue", "penalty", "penalties", "peril", "perils", "perilous",
    "pessimism", "pessimistic", "plummet", "plummeted", "plummeting", "plummets",
    "plunge", "plunged", "plunges", "plunging", "poor", "poorer", "poorest",
    "poorly", "pressure", "pressured", "pressures", "pressuring", "problem",
    "problematic", "problems", "pullback", "questionable", "recall", "recalled",
    "recalling", "recalls", "recession", "recessionary", "recessions", "reduce",
    "reduced", "reduces", "reducing", "reduction", "reductions", "reject",
    "rejected", "rejecting", "rejection", "rejections", "rejects", "restructure",
    "restructured", "restructures", "restructuring", "restructurings", "retrench",
    "retrenched", "retrenches", "retrenching", "retrenchment", "retrenchments",
    "risk", "risked", "riskier", "riskiest", "risking", "risks", "risky",
    "sabotage", "sabotaged", "sabotages", "sabotaging", "sacrifice", "sacrificed",
    "sacrifices", "sacrificing", "scandal", "scandals", "scrutinize", "scrutinized",
    "scrutinizes", "scrutinizing", "scrutiny", "sell", "selloff", "selloffs",
    "selling", "sells", "serious", "seriously", "setback", "setbacks", "severe",
    "severely", "severity", "shock", "shocked", "shocking", "shocks", "short",
    "shortage", "shortages", "shortfall", "shortfalls", "shrink", "shrinkage",
    "shrinking", "shrinks", "shrank", "shrunk", "shut", "shutdown", "shutdowns", "shuts",
    "shutting", "sink", "sinking", "sinks", "sank", "sunk", "slid", "slide", "slides", "sliding",
    "slip", "slipped", "slipping", "slips", "slow", "slowdown", "slowdowns",
    "slowed", "slower", "slowest", "slowing", "slowly", "slows", "sluggish",
    "slump", "slumped", "slumping", "slumps", "stall", "stalled", "stalling",
    "stalls", "stagnant", "stagnate", "stagnated", "stagnates", "stagnating",
    "stagnation", "strain", "strained", "straining", "strains", "stress",
    "stressed", "stresses", "stressful", "stressing", "strike", "strikes",
    "striking", "struck", "struggle", "struggled", "struggles", "struggling",
    "subpoena", "subpoenaed", "subpoenaing", "subpoenas", "sue", "sued", "sues",
    "suffer", "suffered", "suffering", "suffers", "suing", "susceptible",
    "suspend", "suspended", "suspending", "suspends", "suspension", "suspensions",
    "target", "targeted", "targeting", "targets", "terminate", "terminated",
    "terminates", "terminating", "termination", "terminations", "terrible",
    "terribly", "threat", "threaten", "threatened", "threatening", "threatens",
    "threats", "tough", "tougher", "toughest", "trouble", "troubled", "troubles",
    "troublesome", "troubling", "tumble", "tumbled", "tumbles", "tumbling",
    "turmoil", "unable", "uncertain", "uncertainly", "uncertainties", "uncertainty",
    "undermine", "undermined", "undermines", "undermining", "underperform",
    "underperformed", "underperforming", "underperforms", "unfavorable",
    "unfavorably", "unfortunate", "unfortunately", "unlawful", "unlawfully",
    "unprofitable", "unreliable", "unsuccessful", "unsuccessfully", "unstable",
    "untimely", "urgent", "urgently", "violate", "violated", "violates",
    "violating", "violation", "violations", "volatile", "volatility", "vulnerable",
    "warn", "warned", "warning", "warnings", "warns", "weak", "weaken",
    "weakened", "weakening", "weakens", "weaker", "weakest", "weakness",
    "weaknesses", "woes", "worrisome", "worry", "worrying", "worse", "worsen",
    "worsened", "worsening", "worsens", "worst", "worthless", "writedown",
    "writedowns", "writeoff", "writeoffs",
}

FINANCIAL_UNCERTAINTY = {
    "anticipate", "anticipated", "anticipates", "anticipating", "apparent",
    "apparently", "appear", "appeared", "appearing", "appears", "approximate",
    "approximately", "assume", "assumed", "assumes", "assuming", "assumption",
    "assumptions", "believe", "believed", "believes", "believing", "conceivable",
    "conceivably", "conditional", "conditionally", "contingencies", "contingency",
    "contingent", "contingently", "could", "depend", "depended", "depending",
    "depends", "doubt", "doubted", "doubtful", "doubting", "doubts", "estimate",
    "estimated", "estimates", "estimating", "estimation", "estimations",
    "eventual", "eventually", "expect", "expectation", "expectations", "expected",
    "expecting", "expects", "expose", "exposed", "exposes", "exposing",
    "exposure", "exposures", "fluctuate", "fluctuated", "fluctuates",
    "fluctuating", "fluctuation", "fluctuations", "forecast", "forecasted",
    "forecasting", "forecasts", "foreseeable", "foreseen", "hypotheses",
    "hypothetical", "hypothetically", "if", "imprecise", "imprecision",
    "indefinite", "indefinitely", "indeterminable", "indeterminate", "indicate",
    "indicated", "indicates", "indicating", "indication", "indications",
    "indicator", "indicators", "inexact", "intend", "intended", "intending",
    "intends", "intention", "intentions", "likelihood", "likely", "may",
    "maybe", "might", "nearly", "occasionally", "opinion", "opinions", "outlook",
    "pending", "perhaps", "plan", "planned", "planning", "plans", "plausible",
    "plausibly", "possible", "possibly", "potential", "potentially", "predict",
    "predictability", "predicted", "predicting", "prediction", "predictions",
    "predictive", "predicts", "preliminary", "presumably", "presume", "presumed",
    "presumes", "presuming", "presumption", "presumptions", "probabilistic",
    "probabilities", "probability", "probable", "probably", "project",
    "projected", "projecting", "projection", "projections", "projects", "random",
    "randomly", "reestimate", "reestimated", "reestimates", "reestimating",
    "roughly", "seem", "seemed", "seeming", "seemingly", "seems", "should",
    "sometimes", "somewhat", "somewhere", "speculate", "speculated", "speculates",
    "speculating", "speculation", "speculations", "speculative", "speculatively",
    "suggest", "suggested", "suggesting", "suggestion", "suggestions", "suggests",
    "suppose", "supposed", "supposedly", "supposes", "supposing", "tend",
    "tended", "tendency", "tendencies", "tending", "tends", "tentative",
    "tentatively", "uncertain", "uncertainly", "uncertainties", "uncertainty",
    "unclear", "unconfirmed", "undecided", "undefined", "undetermined",
    "unexpected", "unexpectedly", "unforeseen", "unknown", "unknowns",
    "unpredictable", "unpredictably", "unproven", "unquantifiable", "unquantified",
    "unreliable", "unresolved", "unsettled", "unspecified", "unusual",
    "unusually", "variable", "variably", "variance", "variances", "variant",
    "variants", "variation", "variations", "varied", "varies", "vary", "varying",
    "volatile", "volatility",
}

FINANCIAL_LITIGIOUS = {
    "adjudicate", "adjudicated", "adjudicates", "adjudicating", "adjudication",
    "allege", "alleged", "allegedly", "alleges", "alleging", "allegation",
    "allegations", "appeal", "appealed", "appealing", "appeals", "arbitrate",
    "arbitrated", "arbitrates", "arbitrating", "arbitration", "arbitrations",
    "arbitrator", "arbitrators", "claim", "claimant", "claimants", "claimed",
    "claiming", "claims", "complaint", "complaints", "confiscate", "confiscated",
    "confiscates", "confiscating", "confiscation", "convict", "convicted",
    "convicting", "conviction", "convictions", "convicts", "counsel", "countersue",
    "countersued", "countersues", "countersuing", "court", "courts", "crime",
    "crimes", "criminal", "criminally", "criminals", "damages", "decree",
    "decrees", "defend", "defendant", "defendants", "defended", "defending",
    "defends", "depose", "deposed", "deposes", "deposing", "deposition",
    "depositions", "discovery", "enjoin", "enjoined", "enjoining", "enjoins",
    "felonies", "felony", "fraud", "frauds", "fraudulent", "fraudulently",
    "grievance", "grievances", "guilt", "guilty", "hearing", "hearings",
    "illegal", "illegally", "implead", "impleaded", "impleader", "impleading",
    "impleads", "indict", "indicted", "indicting", "indictment", "indictments",
    "indicts", "infringement", "infringements", "injunction", "injunctions",
    "injunctive", "inquiry", "interlocutory", "interrogation", "interrogations",
    "judge", "judges", "judicial", "judiciary", "jurisdiction", "jurisdictional",
    "jurisdictions", "juror", "jurors", "jury", "law", "lawful", "lawfully",
    "laws", "lawsuit", "lawsuits", "lawyer", "lawyers", "legal", "legally",
    "liabilities", "liability", "libel", "libelous", "libels", "litigant",
    "litigants", "litigate", "litigated", "litigates", "litigating", "litigation",
    "litigations", "mistrial", "mistrials", "motion", "motions", "offence",
    "offences", "offend", "offended", "offender", "offenders", "offending",
    "offends", "offense", "offenses", "order", "ordered", "ordering", "orders",
    "perjure", "perjured", "perjures", "perjuries", "perjuring", "perjury",
    "plaintiff", "plaintiffs", "plea", "plead", "pleaded", "pleading", "pleadings",
    "pleads", "pleas", "pled", "prejudice", "prejudiced", "prejudices",
    "prejudicing", "prejudicial", "prison", "prisoned", "prisoner", "prisoners",
    "prisoning", "prisons", "probation", "probationary", "probations", "prosecute",
    "prosecuted", "prosecutes", "prosecuting", "prosecution", "prosecutions",
    "prosecutor", "prosecutors", "punish", "punished", "punishes", "punishing",
    "punishment", "punishments", "punitive", "remand", "remanded", "remanding",
    "remands", "remedy", "remedies", "restrain", "restrained", "restraining",
    "restrains", "restraint", "restraints", "rule", "ruled", "rules", "ruling",
    "rulings", "sanction", "sanctioned", "sanctioning", "sanctions", "sentence",
    "sentenced", "sentences", "sentencing", "settle", "settled", "settlement",
    "settlements", "settles", "settling", "severance", "slander", "slanderous",
    "slanders", "statute", "statutes", "statutory", "subpoena", "subpoenaed",
    "subpoenaing", "subpoenas", "sue", "sued", "sues", "suing", "suit", "suits",
    "summon", "summoned", "summoning", "summons", "testify", "testified",
    "testifies", "testifying", "testimonial", "testimonies", "testimony",
    "tort", "tortious", "torts", "trial", "trials", "tribunal", "tribunals",
    "verdict", "verdicts", "violate", "violated", "violates", "violating",
    "violation", "violations", "violator", "violators", "witness", "witnessed",
    "witnesses", "witnessing",
}
